####################################################################
# call.jekyll-ghpages-tagging.yml
####################################################################
# This file is provided as an example of how to call the
# jekyll-ghpages-tagging reusable workflow.
#
# File:         call.jekyll-ghpages-tagger.yml
# Author:       Ragdata
# Date:         30/06/2024
# License:      MIT License
# Copyright:    Copyright © 2024 Darren (Ragdata) Poulton
####################################################################
name: Jekyll GitHub-Pages Tagging Workflow

on:
    # Trigger whenever .md files in the docs/_posts directory on the master branch are pushed
    push:
        branches:
            - master
        paths:
            - "docs/_posts/*.md"
    # Allows for manual triggering via Actions tab
    workflow_dispatch:

jobs:
    call_reusable_workflow:
        permissions:
            contents: read
            pages: write
            id-token: write
        uses: ragdata/reusable-workflows/.github/workflows/jekyll-ghpages-tagging.yml@master
        with:
            posts_dir: "docs/_posts"
            tags_dir: "docs/_tags"
            tags_layout: "tags"
            feeds_dir: "docs/_feeds"
            feeds_layout: "feed"
            github_token: ${{ secrets.GITHUB_TOKEN }}
