extends: relman.base.yml
name: Ragdata's Reusable Workflows
description: The reusable workflows that I actually use to manage my repos
version: v0.1.0
copyright: Copyright © 2024 Redeyed Technologies
website: https://github.com/ragdata/reusable-workflows
repo_url: https://github.com/ragdata/reusable-workflows
authors:
    - username: Ragdata
      first_name: Darren
      surname: Poulton
      email: ragdata@ragdata.dev
      location: Brisbane, Australia
      affiliation: Redeyed Technologies
changelog:
    template: changelog.md
    file: CHANGELOG.md
    style: per_release
    create: true
release:
    template: release.md
    create: true
pull_request:
    template: pull_request.md
    create: true
