extends: .release.base.yml
name: Ragdata's Reusable Workflows
description: The reusable workflows that I actually use to manage my repos
version: 0.1.0
copyright: Copyright © 2024 Redeyed Technologies
website: https://github.com/ragdata/reusable-workflows
repo_url: https://github.com/ragdata/reusable-workflows
authors:
    - username: Ragdata
      first_name: Darren
      surname: Poulton
      email: ragdata@ragdata.dev
      affiliation: Redeyed Technologies
protect_prod: true
changelog: true
logged:
    - feat
    - ci
    - fix
    - perf
    - style
    - docs
