failure-threshold: info                 # name of threshold level (error | warning | info | style | ignore | none)
format: json                            # Output format (tty | json | checkstyle | codeclimate | gitlab_codeclimate | gnu | codacy)
#ignored: [string]                      # list of rules
#label-schema:                           # See Linting Labels below for specific label-schema details
#    author: Ragdata                     # Your name
#    contact: ragdata@ragdata.net        # email address
#    created: 2024-07-07 02:07:37+10:00  # rfc3339 datetime
#    version: 1.0                        # semver
#    documentation: https://github.com/ragdata/reusable-workflows/   # url
#    git-revision: f95aa80               # hash
#    license: string                     # spdx
no-color: false                          # true | false
no-fail: false                           # true | false
#override:
#    error: [string]                     # list of rules
#    warning: [string]                   # list of rules
#    info: [string]                      # list of rules
#    style: [string]                     # list of rules
strict-labels: false                     # true | false
disable-ignore-pragma: false             # true | false
# registry or list of registries
trustedRegistries:
    - docker.io
    - ghcr.io

