####################################################################
# call-local.mega-linter.yml
####################################################################
# Mega Linter Local Caller Workflow
#
# File:         call-local.mega-linter.yml
# Version:      1.0
# Author:       Ragdata
# Date:         07/07/2024
# License:      MIT License
# Copyright:    Copyright © 2024 Darren (Ragdata) Poulton
####################################################################
name: MegaLinter

on:
    # Trigger whenever files are pushed to any branch of the repo
    push: null
    # Trigger whenever a pull_request is raised on the master branch
    pull_request:
        branches:
            - master
    # Allows for manual triggering via the Actions tab
    workflow_dispatch:

jobs:

    call_reusable_workflow:
        permissions:
            contents: write
            issues: write
            pull-requests: write
        uses: ./.github/workflows/mega-linter.yml@master
