####################################################################
# jekyll-ghpages-tagging.yml
####################################################################
# Jekyll GitHub-Pages Tagging Reusable Workflow
#
# This workflow scans files in the _posts directory of a Jekyll
# GH-Pages site to check for new tags.  If new tags are found, a file
# is created for each new tag under the '_tags' and '_feeds' folders
# which allows all articles associated with the tag to be displayed
# in each format.
#
# File:         jekyll-ghpages-tagger.yml
# Author:       Ragdata
# Date:         30/06/2024
# License:      MIT License
# Copyright:    Copyright © 2024 Darren (Ragdata) Poulton
####################################################################
name: Jekyll GitHub-Pages Tagging Reusable Workflow

on:
    # Allows this workflow to be called by other workflows
    workflow_call:
        inputs:
            posts_dir:
                description: "Path to '_posts' directory from root"
                required: true
                type: string
                default: "_posts"
            tags_dir:
                description: "Path to '_tags' directory from root"
                required: true
                type: string
                default: "_tags"
            tags_layout:
                description: "Layout used by tag files"
                required: true
                type: string
                default: "tags"
            feeds_dir:
                description: "Path to '_feeds' directory from root"
                required: false
                type: string
                default: "_feeds"
            feeds_layout:
                description: "Layout used by feed files"
                required: false
                type: string
                default: "feed"
            prune_tags:
                description: "Remove unused tags"
                required: false
                type: boolean
                default: true
        secrets:
            token:
                required: true

jobs:

    tag:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Call Tag Generator Action
              uses: ragdata/jekyll-ghpages-tagging@master
              env:
                  GITHUB_TOKEN: ${{ secrets.token }}
              with:
                  posts_dir: ${{ inputs.posts_dir }}
                  tags_dir: ${{ inputs.tags_dir }}
                  tags_layout: ${{ inputs.tags_layout }}
                  feeds_dir: ${{ inputs.feeds_dir }}
                  feeds_layout: ${{ inputs.feeds_layout }}
