####################################################################
# release-manager.yml
####################################################################
# Ragdata's Release Manager Reusable Workflow
#
# File:         release-manager.yml
# Version:      1.0
# Author:       Ragdata
# Date:         27/07/2024
# License:      MIT License
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
name: Release Manager - Reusable

on:
    # Allows this workflow to be called by other workflows
    workflow_call:
        inputs:
            version:
                description: "Release Version"
                required: false
                type: string
            type:
                description: "Bump Type"
                required: false
                type: string
            branch:
                description: "Branch / Tag to create release from"
                required: false
                type: string
            pre_release:
                description: "Mark as pre-release?"
                required: false
                type: boolean
                default: false
            draft:
                description: "Draft release?"
                required: false
                type: boolean
                default: false
        secrets:
            token:
                required: true

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:

    manage_release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            ########################################################
            # Checkout Repository
            ########################################################
            - name: Checkout Repository
              uses: actions/checkout@v4

            ########################################################
            # Manage Release
            ########################################################
            - name: Manage Release
              uses: ragdata/release-manager.action@master
              with:
                  version: ${{ inputs.version }}
                  type: ${{ inputs.type }}
                  branch: ${{ inputs.branch }}
                  pre_release: ${{ inputs.pre_release }}
              env:
                  GITHUB_TOKEN: ${{ secrets.token }}
