####################################################################
# release-manager.call-local.yml
####################################################################
# Ragdata's Release Manager Local Caller Workflow
#
# File:         release-manager.call-local.yml
# Version:      1.0
# Author:       Ragdata
# Date:         27/07/2024
# License:      MIT License
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
name: Release Manager

on:

    # Allows for manual triggering via the Actions tab
    workflow_dispatch:
        inputs:
            version:
                description: "Release Version"
                required: false
                type: string
            type:
                description: "Bump Type"
                required: false
                type: choice
                options:
                    - version
                    - first
                    - patch
                    - minor
                    - major
            branch:
                description: "Branch / Tag to create release from"
                required: false
                type: string
            pre_release:
                description: "Mark as pre-release?"
                required: false
                type: boolean
                default: false
            draft:
                description: "Draft release?"
                required: false
                type: boolean
                default: false

jobs:

    call_reusable_workflow:
        permissions:
            contents: write
        uses: ./.github/workflows/release-manager.yml
        with:
            version: ${{ inputs.version }}
            type: ${{ inputs.type }}
            branch: ${{ inputs.branch }}
            pre_release: ${{ inputs.pre_release }}
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}
